theme: minima
# 仅列出需要高亮悬浮显示的词语
highlight_words:
  - Regenerative Orthopedics
  - Regenerative Medicine
  - Biological Medicine/Biomedicine
  - Tissue Engineering
  - Bioprinting
  - Cancer Research
  - Stem Cell
  - Human Structure and Repair
  - Cell Biology
